apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: CamWills-2nd
spec:
  encryptedData:
    token: AgAEFt1+mf/4gSklxu7wWbPjzG56x8NFOPcnt+TBajY63Dt1i8vm++ez4cCgDrEm483FEptpdcreg+d6DcZyPag0yVIXqOIDLfnAg47neYCXva9T3vs/vtlujK6EAvnrXOUanZuiWI9tOVvRG8I9Ewqo/j4G9zID7WP59hlKF7TEtYf2LpU050ZNbevT+CDFlNz/XhbEM3tNm7uSOCrn4boK6TGW/iCXygFRqRH99YzSYRNEHbbm/y40deoCadb96hH+oSBXseKRNOzfIKvF4dfg2LvSKRoBl8XUOBC+IH+r/kKo7Zy//MNWaQd3zMRxHU4UM1f8u5boyn6kkFwuDAVbD+ZIHGVf0EdVr1Lqjru+07LnQPVgmvUBzPA9aRHmzbpRIAecLQ87Stq5s/dWeunicoXizM3MfxChuq64OvSAoU/4McTKHIpKWEK5jt4qM104W8WvMhV9Z4nafTGjP9eb6KdoQu/6OlQZ5FURqNEZoBgqWF6rvFR0f6G2VN5SGiAHfp+x8PigjPEQ3oyPnGexMY9rNUJWpJnndoMuTKvqt0jFHnkeSO2pETf+kaoz5SFITQZgsgOK+mmCxnQfEvyLkTroRG40tFF1tzkYlIyUGL1QcdWrDWfcrWkVKxZnX0qOLEnh4W0Xic2fvukEmHEmQRVgKcmcvAPoN+Apt0Y7XaxPvRxAZwEUy9MpOOgDtmaOICd4orcQYYd0o15ZAbxi5AkxHEYdIUXMeLy+NYNbx0wxSjqGO0EV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: CamWills-2nd

