apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-cwills
spec:
  encryptedData:
    token: AgA2uks8ha+5Z/LN5hUD3E1W2u5f9fTjlSptImWp8QR24NG5B+OdNklR3H01NPVI7zlLRfGRzhvHc2SXamMClGsL5FQvn+vBIoLK4M/as9mqpMs2abxe+N/EvDRQEQpLZ1qlZW2DBdmY/sNHcy3io7+YhJkzzVXCj5w41moRNpu9Jl1YBYKrQ6JOUwCHiLViw9S0nnN4Ha5PVOx35wRD+qk5D7++4C2iqz39dBiPVPTro0DWe1lSsn6509cdiM3WiXm5wXK0q8g9GKVyt/8NOPWKpZxiq9L/wNVz4XXTemjlrXwZoiPWDkMuNA72BoHVDcds8V0lgcAcloBF3mehmM2tiO+CzV2DDLaJwpmAAZYrSNE9YTnuAdTbkjCzFBDiKa862kDbyxmGviafKFPQlbAd3r9p38WSmtpRxr66+IuOPwb8ZBlkQDuMmGkgMrFb23ql6sMCSm8GhDCs80G8rpsPgkQEYFxl1Mb+8VgxZCGtADli+iKxD7MJtVZkQ2YcBX6TaZkB93/AiHNjXz2SxSAYftXh/QEl1XX8TckbhRPJ7qnKMlQoutriXL6as+U0kRMZckWZZHyNT71xxhM7RT9U2QX8/nka/A3tNwicZ/wUHnDnrVFK9K0ZCcrYW7S8t+W2R2sGhIsjqdh8+fqDEnpPOrfKBL1vfI7fAxcBVIjNUDRSIaploIXET83gYnUY+QQx23iSOwbXVcIQOUPD8/bwf7pp/YQOrF83lhBD7wDawfwkyTS9Vijj
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-cwills

