apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgAk05ww+f/nqb9PD9IYeQnYPsNeVGbQAZZfHlP03Kta9H7NyuHOpLpORoHwjO7bTJF94Dv8U1Q7gsSVgu+/mFnPEwmBkMLZ1tViLiLlOsDMgdYv+hpLsYihR5evIr313wMVcpZ9AYwxjya2aaK7hiCqwJW7XARt022J51iDrI06EZVxWRszNoKXT3EkILlZL8dWoV9WqPZD5We31YYYvwhNx1L9O9WQPpur3LYOAzX2wMmLxdru9jJZjUYZjCaCqxhkENLvcoLch6SBkQcCBni3t1ikNn6UBRpTDmOgEDkH4NQH270RTRGMJbikQiQ2acG1vHaGEVP4HrKheOlD005TfARZHTCtMv6jaONEccPNhiFDDmJttWH4LHROarqSQXmxWsKBsqFnxitzTxCnUHTE/PpQb4cT99LIBRzReS+vxmyoPn9o4YBNvwRELVScJeavFd2YVaQxPze9KTJdDuKHFASbatVDtnH6rNQPKA9pbmDu5Tv9m8hdwuwncCoZvtiZn3FfSnyNDLp+o3QXvTu8v2UMBUKaTu30dwUhho8VfOLG3bMYer9JAFJEBisZpYYO45K+CGRZsiBP8B4XbEsp5bBDv6CHsgSz52HIsqwc0fzkqSdP9vx+IRLqLkf9nClhfVW8mNz9GsQNwPqkEQZAkaOAip2K4yHOa0bBeV2yDTlu0WkrR6tr2iLYK7EUcvPhYmcZlLTbv0COrMsjEMUWkKtIAFNeMZku5mckZP3G1Yil2TM6i0nX
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

