apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-newconfig-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
